-- 1. 建立資料表 (如果尚未建立)
CREATE TABLE IF NOT EXISTS Skill (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    author TEXT,
    category TEXT,
    tags TEXT, -- 儲存為 JSON 字串
    downloadCount INTEGER DEFAULT 0,
    createdAt TEXT,
    version TEXT,
    folderName TEXT
);

-- 2. 批次新增技能資料

-- [Collaboration & Project Management]
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (22, 'atlassian-mcp', 'Integrate Jira and Confluence workflows via Model Context Protocol.', 'Jeffallan', 'Collaboration & Project Management', '["Jira","Confluence","MCP"]', 840, '2025-02-28', '1.0.0', 'atlassian-mcp');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (39, 'feature-forge', 'Gathering requirements, conducting workshops, and defining comprehensive feature specifications.', 'Jeffallan', 'Collaboration & Project Management', '["Requirements","Product","Planning"]', 320, '2025-03-03', '1.0.0', 'feature-forge');

-- [Document Skills]
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (1, 'docx', 'Create, edit, analyze Word docs with tracked changes, comments, formatting.', 'Anthropic', 'Document Skills', '["Document","Word","Editing"]', 120, '2025-01-01', '1.0.0', 'docx');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (2, 'pdf', 'Extract text, tables, metadata, merge & annotate PDFs.', 'Anthropic', 'Document Skills', '["Document","PDF","Extraction"]', 340, '2025-01-05', '1.0.0', 'pdf');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (3, 'pptx', 'Read, generate, and adjust slides, layouts, templates.', 'Anthropic', 'Document Skills', '["Document","PowerPoint","Slides"]', 210, '2025-01-10', '1.0.0', 'pptx');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (4, 'xlsx', 'Spreadsheet manipulation: formulas, charts, data transformations.', 'Anthropic', 'Document Skills', '["Document","Excel","Data"]', 450, '2025-01-15', '1.0.0', 'xlsx');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (5, 'revealjs-skill', 'Generate polished, professional presentations using the Reveal.js HTML presentation framework.', 'ryanbbrown', 'Document Skills', '["Presentation","Reveal.js","HTML"]', 180, '2025-02-01', '1.0.0', 'revealjs-skill');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (100, 'xlsx', 'Use this skill any time a spreadsheet file is the primary input or output (Excel, CSV, TSV).', 'Anthropic', 'Document Skills', '["Excel","CSV","Spreadsheet","Data"]', 520, '2025-03-03', '1.0.0', 'xlsx');

-- [Data & Analysis]
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (9, 'csv-data-summarizer', 'Automatically analyzes CSVs: columns, distributions, missing data, correlations.', 'coffeefuelbump', 'Data & Analysis', '["CSV","Data","Summary"]', 720, '2025-01-30', '1.0.2', 'csv-data-summarizer');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (10, 'postgres', 'Execute safe read-only SQL queries against PostgreSQL databases.', 'sanjay3290', 'Data & Analysis', '["SQL","PostgreSQL","Database"]', 610, '2025-02-05', '1.0.0', 'postgres');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (29, 'database-optimizer', 'investigating slow queries, analyzing execution plans, and index design.', 'Jeffallan', 'Data & Analysis', '["Database","SQL","Optimization"]', 370, '2025-03-03', '1.0.0', 'database-optimizer');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (40, 'fine-tuning-expert', 'Fine-tuning LLMs, training custom models, or optimizing model performance for specific tasks.', 'Jeffallan', 'Data & Analysis', '["LLM","AI","ML"]', 520, '2025-03-03', '1.0.0', 'fine-tuning-expert');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (57, 'postgres-pro', 'Use when optimizing PostgreSQL queries, configuring replication, or implementing advanced database features.', 'Jeffallan', 'Data & Analysis', '["PostgreSQL","SQL","Optimization"]', 310, '2025-03-03', '1.0.0', 'postgres-pro');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (58, 'rag-architect', 'Use when building RAG systems, vector databases, or knowledge-grounded AI applications.', 'Jeffallan', 'Data & Analysis', '["RAG","Vector DB","AI"]', 450, '2025-03-03', '1.0.0', 'rag-architect');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (77, 'spark-engineer', 'Building Apache Spark applications, distributed data processing pipelines, or optimizing big data workloads.', 'Jeffallan', 'Data & Analysis', '["Spark","Big Data","ETL"]', 370, '2025-03-03', '1.0.0', 'spark-engineer');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (80, 'sql-pro', 'Use when optimizing SQL queries, designing database schemas, or tuning database performance.', 'Jeffallan', 'Data & Analysis', '["SQL","Database","Optimization"]', 310, '2025-03-03', '1.0.0', 'sql-pro');

-- [Media & Content]
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (18, 'algorithmic-art', 'Generate living algorithms and generative art using p5.js.', 'Anthropic', 'Media & Content', '["Generative Art","p5.js","Creative"]', 1100, '2025-02-15', '1.0.0', 'algorithmic-art');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (19, 'canvas-design', 'Create museum-quality visual designs and artistic canvases.', 'Anthropic', 'Media & Content', '["Design","Art","Visual"]', 920, '2025-02-18', '1.0.0', 'canvas-design');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (20, 'brand-guidelines', 'Apply Anthropic official brand colors and typography to any artifact.', 'Anthropic', 'Media & Content', '["Branding","Styling","Guidelines"]', 1500, '2025-01-10', '1.0.0', 'brand-guidelines');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (45, 'game-developer', 'Building game systems, implementing Unity/Unreal features, or optimizing game performance.', 'Jeffallan', 'Media & Content', '["Unity","Unreal","GameDev"]', 480, '2025-03-03', '1.0.0', 'game-developer');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (78, 'slack-gif-creator', 'Create animated GIFs optimized for Slack with dimensions, validation tools, and easing functions.', 'SKILLS All-in-one', 'Media & Content', '["Slack","GIF","Design"]', 420, '2025-03-03', '1.0.0', 'slack-gif-creator');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (88, 'theme-factory', 'Toolkit for styling artifacts with professional themes, colors, and fonts.', 'Jeffallan', 'Media & Content', '["Design","Themes","Styling"]', 370, '2025-03-03', '1.0.0', 'theme-factory');

-- [Writing & Research]
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (11, 'article-extractor', 'Extract full article text and metadata from web pages.', 'michalparkola', 'Writing & Research', '["Scraping","Metadata","Web"]', 430, '2025-02-15', '1.0.0', 'article-extractor');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (21, 'brainstorming', 'Transform rough ideas into fully-formed designs through structured questioning.', 'obra', 'Writing & Research', '["Ideas","Requirements","Design"]', 2100, '2025-01-05', '1.0.0', 'brainstorming');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (34, 'doc-coauthoring', 'Guide users through a structured workflow for co-authoring documentation.', 'SKILLS All-in-one', 'Writing & Research', '["Documentation","Co-authoring","Writing"]', 250, '2025-03-03', '1.0.0', 'doc-coauthoring');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (48, 'internal-comms', 'Write internal company communications (status reports, newsletters, FAQs, incident reports).', 'Jeffallan', 'Writing & Research', '["Comms","Internal","Writing"]', 190, '2025-03-03', '1.0.0', 'internal-comms');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (87, 'the-fool', 'Use when challenging ideas, plans, decisions, or proposals using structured critical reasoning.', 'Jeffallan', 'Writing & Research', '["Critical Thinking","Red Team","Reasoning"]', 290, '2025-03-03', '1.0.0', 'the-fool');

-- [Security & Web Testing]
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (23, 'chaos-engineer', 'Design chaos experiments and build systems that get stronger under stress.', 'Jeffallan', 'Security & Web Testing', '["Chaos Engineering","Resilience","Testing"]', 390, '2025-03-02', '1.0.0', 'chaos-engineer');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (75, 'secure-code-guardian', 'Implementing authentication/authorization, securing user input, or preventing OWASP Top 10 vulnerabilities.', 'Jeffallan', 'Security & Web Testing', '["Security","Auth","OWASP"]', 450, '2025-03-03', '1.0.0', 'secure-code-guardian');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (76, 'security-reviewer', 'Conducting security audits, reviewing code for vulnerabilities, or analyzing infrastructure security.', 'Jeffallan', 'Security & Web Testing', '["Audit","Vulnerability","Pentest"]', 390, '2025-03-03', '1.0.0', 'security-reviewer');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (95, 'webapp-testing', 'Toolkit for interacting with and testing local web applications using Playwright.', 'Jeffallan', 'Security & Web Testing', '["Testing","Playwright","Web"]', 380, '2025-03-03', '1.0.0', 'webapp-testing');

-- [Utility & Automation]
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (32, 'dispatching-parallel-agents', 'Dispatch one agent per independent problem domain to work concurrently.', 'SKILLS All-in-one', 'Utility & Automation', '["Agent","Parallel","Multi-task"]', 880, '2025-03-03', '1.0.0', 'dispatching-parallel-agents');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (37, 'executing-plans', 'Execute a written implementation plan with review checkpoints.', 'Jeffallan', 'Utility & Automation', '["Workflow","Execution","Planning"]', 640, '2025-03-03', '1.0.0', 'executing-plans');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (41, 'finishing-a-development-branch', 'Guide completion of development work by presenting structured options for merge, PR, or cleanup.', 'Jeffallan', 'Utility & Automation', '["Git","Workflow","PR"]', 510, '2025-03-03', '1.0.0', 'finishing-a-development-branch');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (79, 'skill-creator', 'Create new skills, modify and improve existing skills, and measure skill performance with evals.', 'SKILLS All-in-one', 'Utility & Automation', '["Agent","Skills","Development"]', 850, '2025-03-03', '1.0.0', 'skill-creator');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (13, 'skill-master', 'The ultimate AI Agent Skill Master for analyzing, architecting, and authoring skills.', 'SKILLS All-in-one', 'Utility & Automation', '["Agent","Architecture","Writing"]', 5000, '2026-03-03', '1.0.0', 'skill-master');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (82, 'subagent-driven-development', 'Use when executing implementation plans with independent tasks in the current session.', 'SKILLS All-in-one', 'Utility & Automation', '["Workflow","Agent","Implementation"]', 420, '2025-03-03', '1.0.0', 'subagent-driven-development');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (90, 'using-git-worktrees', 'Use when starting feature work that needs isolation from current workspace or before executing plans.', 'Jeffallan', 'Utility & Automation', '["Git","Worktree","Workflow"]', 310, '2025-03-03', '1.0.0', 'using-git-worktrees');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (91, 'using-superpowers', 'Use when starting any conversation - establishes how to find and use skills.', 'SKILLS All-in-one', 'Utility & Automation', '["Agent","Skill","Workflow"]', 1200, '2025-03-03', '1.0.0', 'using-superpowers');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (99, 'writing-skills', 'Use when creating new skills, editing existing skills, or verifying skills work before deployment.', 'Jeffallan', 'Utility & Automation', '["Skills","Documentation","TDD","Automation"]', 350, '2025-03-03', '1.0.0', 'writing-skills');

-- [Development & Code Tools]
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (6, 'web-artifacts-builder', 'Suite of tools for creating elaborate, multi-component HTML artifacts using React, Tailwind, and shadcn/ui.', 'Anthropic', 'Development & Code Tools', '["React","Tailwind","Artifacts"]', 890, '2025-01-20', '1.1.0', 'web-artifacts-builder');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (7, 'test-driven-development', 'Use when implementing any feature or bugfix, before writing implementation code.', 'obra', 'Development & Code Tools', '["TDD","Testing","Quality"]', 560, '2025-01-25', '1.0.0', 'test-driven-development');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (8, 'claude-starter', 'Production-ready Claude Code configuration template with 40 auto-activating skills.', 'raintree-technology', 'Development & Code Tools', '["Starter","Configuration","Template"]', 1200, '2025-02-10', '1.5.0', 'claude-starter');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (12, 'oiloil-ui-ux-guide', 'Modern UI/UX guidance and review skill with guide and review modes.', 'oil-oil', 'Development & Code Tools', '["UI/UX","Design","Review"]', 950, '2025-02-20', '1.0.0', 'oiloil-ui-ux-guide');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (14, 'angular-architect', 'Build enterprise Angular apps with signals and standalone components.', 'Jeffallan', 'Development & Code Tools', '["Angular","Signals","Architecture"]', 420, '2025-02-25', '1.0.0', 'angular-architect');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (15, 'api-designer', 'Design REST/GraphQL APIs with OpenAPI 3.1 standards.', 'Jeffallan', 'Development & Code Tools', '["API","OpenAPI","Design"]', 680, '2025-02-26', '1.0.0', 'api-designer');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (16, 'architecture-designer', 'Architect scalable distributed systems and document ADRs.', 'Jeffallan', 'Development & Code Tools', '["System Design","ADR","Scalability"]', 530, '2025-02-27', '1.0.0', 'architecture-designer');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (17, 'cli-developer', 'Build fast, intuitive cross-platform CLI tools.', 'Jeffallan', 'Development & Code Tools', '["CLI","Terminal","DX"]', 310, '2025-03-01', '1.0.0', 'cli-developer');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (36, 'embedded-systems', 'Developing firmware for microcontrollers, implementing RTOS applications, or optimizing power consumption.', 'Jeffallan', 'Development & Code Tools', '["Embedded","Firmware","RTOS"]', 280, '2025-03-03', '1.0.0', 'embedded-systems');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (38, 'fastapi-expert', 'Build high-performance async Python APIs with FastAPI and Pydantic V2.', 'Jeffallan', 'Development & Code Tools', '["Python","FastAPI","Async"]', 450, '2025-03-03', '1.0.0', 'fastapi-expert');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (42, 'flutter-expert', 'Building cross-platform applications with Flutter 3+ and Dart.', 'Jeffallan', 'Development & Code Tools', '["Flutter","Dart","Mobile"]', 310, '2025-03-03', '1.0.0', 'flutter-expert');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (43, 'frontend-design', 'Create distinctive, production-grade frontend interfaces with high design quality.', 'Jeffallan', 'Development & Code Tools', '["Frontend","UI","Aesthetics"]', 720, '2025-03-03', '1.0.0', 'frontend-design');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (44, 'fullstack-guardian', 'Implementing features across frontend and backend with security built-in from the start.', 'Jeffallan', 'Development & Code Tools', '["Fullstack","Security","API"]', 580, '2025-03-03', '1.0.0', 'fullstack-guardian');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (46, 'golang-pro', 'Building Go applications requiring concurrent programming, microservices, or high-performance systems.', 'Jeffallan', 'Development & Code Tools', '["Go","Concurrency","Microservices"]', 390, '2025-03-03', '1.0.0', 'golang-pro');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (47, 'graphql-architect', 'Designing GraphQL schemas, implementing Apollo Federation, or building real-time subscriptions.', 'Jeffallan', 'Development & Code Tools', '["GraphQL","Apollo","Federation"]', 410, '2025-03-03', '1.0.0', 'graphql-architect');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (49, 'java-architect', 'Building enterprise Java applications with Spring Boot 3.x, microservices, or reactive programming.', 'Jeffallan', 'Development & Code Tools', '["Java","Spring Boot","Enterprise"]', 340, '2025-03-03', '1.0.0', 'java-architect');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (50, 'php-pro', 'Use when building PHP applications with modern PHP 8.3+ features, Laravel, or Symfony frameworks.', 'Jeffallan', 'Development & Code Tools', '["PHP","Laravel","Symfony"]', 260, '2025-03-03', '1.0.0', 'php-pro');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (51, 'python-pro', 'Use when building Python 3.11+ applications requiring type safety, async programming, or production-grade patterns.', 'Jeffallan', 'Development & Code Tools', '["Python","Async","Type Safety"]', 480, '2025-03-03', '1.0.0', 'python-pro');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (52, 'rails-expert', 'Use when building Rails 7+ web applications with Hotwire, real-time features, or background job processing.', 'Jeffallan', 'Development & Code Tools', '["Rails","Ruby","Hotwire"]', 310, '2025-03-03', '1.0.0', 'rails-expert');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (53, 'react-expert', 'Use when building React 18+ applications requiring component architecture, hooks patterns, or state management.', 'Jeffallan', 'Development & Code Tools', '["React","Hooks","TypeScript"]', 920, '2025-03-03', '1.0.0', 'react-expert');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (54, 'react-native-expert', 'Use when building cross-platform mobile applications with React Native or Expo.', 'Jeffallan', 'Development & Code Tools', '["React Native","Expo","Mobile"]', 380, '2025-03-03', '1.0.0', 'react-native-expert');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (55, 'receiving-code-review', 'Use when receiving code review feedback, before implementing suggestions, especially if feedback seems unclear or technically questionable.', 'Jeffallan', 'Development & Code Tools', '["Code Review","Workflow","Quality"]', 210, '2025-03-03', '1.0.0', 'receiving-code-review');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (56, 'requesting-code-review', 'Use when completing tasks, implementing major features, or before merging to verify work meets requirements.', 'Jeffallan', 'Development & Code Tools', '["Code Review","Verification","Workflow"]', 240, '2025-03-03', '1.0.0', 'requesting-code-review');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (70, 'rust-engineer', 'Use when building Rust applications requiring memory safety, systems programming, or zero-cost abstractions.', 'Jeffallan', 'Development & Code Tools', '["Rust","Systems","Performance"]', 310, '2025-03-03', '1.0.0', 'rust-engineer');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (71, 'salesforce-developer', 'Developing Salesforce applications, Apex code, Lightning Web Components, SOQL queries, or integrations.', 'Jeffallan', 'Development & Code Tools', '["Salesforce","Apex","CRM"]', 280, '2025-03-03', '1.0.0', 'salesforce-developer');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (72, 'shopify-expert', 'Building Shopify themes, apps, custom storefronts, or e-commerce solutions.', 'Jeffallan', 'Development & Code Tools', '["Shopify","Liquid","E-commerce"]', 340, '2025-03-03', '1.0.0', 'shopify-expert');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (73, 'spec-miner', 'Understanding legacy or undocumented systems, creating documentation, or extracting specifications from implementations.', 'Jeffallan', 'Development & Code Tools', '["Reverse Engineering","Documentation","Legacy"]', 290, '2025-03-03', '1.0.0', 'spec-miner');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (74, 'spring-boot-engineer', 'Building Spring Boot 3.x applications, microservices, or reactive Java applications.', 'Jeffallan', 'Development & Code Tools', '["Spring Boot","Java","Backend"]', 410, '2025-03-03', '1.0.0', 'spring-boot-engineer');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (81, 'sre-engineer', 'Use when defining SLIs/SLOs, managing error budgets, or building reliable systems at scale.', 'Jeffallan', 'Development & Code Tools', '["SRE","Reliability","Monitoring"]', 340, '2025-03-03', '1.0.0', 'sre-engineer');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (83, 'swift-expert', 'Use when building iOS/macOS applications with Swift 5.9+, SwiftUI, or async/await concurrency.', 'Jeffallan', 'Development & Code Tools', '["Swift","iOS","SwiftUI"]', 280, '2025-03-03', '1.0.0', 'swift-expert');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (84, 'systematic-debugging', 'Use when encountering any bug, test failure, or unexpected behavior, before proposing fixes.', 'Jeffallan', 'Development & Code Tools', '["Debugging","RC","Methodology"]', 510, '2025-03-03', '1.0.0', 'systematic-debugging');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (85, 'terraform-engineer', 'Use when implementing infrastructure as code with Terraform across AWS, Azure, or GCP.', 'Jeffallan', 'Development & Code Tools', '["Terraform","IaC","Infra"]', 390, '2025-03-03', '1.0.0', 'terraform-engineer');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (86, 'test-master', 'Use when writing tests, creating test strategies, or building automation frameworks.', 'Jeffallan', 'Development & Code Tools', '["Testing","QA","Automation"]', 450, '2025-03-03', '1.0.0', 'test-master');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (89, 'typescript-pro', 'Use when building TypeScript applications requiring advanced type systems or generics.', 'Jeffallan', 'Development & Code Tools', '["TypeScript","Generics","Typing"]', 680, '2025-03-03', '1.0.0', 'typescript-pro');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (92, 'verification-before-completion', 'Use when about to claim work is complete, fixed, or passing, before committing.', 'SKILLS All-in-one', 'Development & Code Tools', '["Validation","Testing","Verification"]', 850, '2025-03-03', '1.0.0', 'verification-before-completion');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (93, 'vue-expert', 'Use when building Vue 3 applications with Composition API, Nuxt 3, or Quasar.', 'Jeffallan', 'Development & Code Tools', '["Vue","Composition API","Nuxt"]', 420, '2025-03-03', '1.0.0', 'vue-expert');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (94, 'vue-expert-js', 'Use when building Vue 3 applications with JavaScript only (no TypeScript).', 'Jeffallan', 'Development & Code Tools', '["Vue","JavaScript","JSDoc"]', 310, '2025-03-03', '1.0.0', 'vue-expert-js');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (96, 'websocket-engineer', 'Use when building real-time communication systems with WebSockets or Socket.IO.', 'Jeffallan', 'Development & Code Tools', '["WebSocket","Socket.IO","Real-time"]', 250, '2025-03-03', '1.0.0', 'websocket-engineer');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (97, 'wordpress-pro', 'Use when developing WordPress themes, plugins, customizing Gutenberg blocks, or optimizing WordPress performance.', 'Jeffallan', 'Development & Code Tools', '["WordPress","WooCommerce","Gutenberg"]', 180, '2025-03-03', '1.0.0', 'wordpress-pro');
INSERT INTO Skill (id, name, description, author, category, tags, downloadCount, createdAt, version, folderName) VALUES (98, 'writing-plans', 'Use when you have a spec or requirements for a multi-step task, before touching code. Write comprehensive implementation plans assuming the engineer has zero context.', 'Jeffallan', 'Development & Code Tools', '["Planning","Implementation","Workflow"]', 420, '2025-03-03', '1.0.0', 'writing-plans');
