-- 1. 建立資料表 (如果尚未建立)
CREATE TABLE IF NOT EXISTS Skill (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    nameZh TEXT,
    description TEXT,
    descriptionZh TEXT,
    author TEXT,
    category TEXT,
    tags TEXT, -- 儲存為 JSON 字串
    downloadCount INTEGER DEFAULT 0,
    createdAt TEXT,
    version TEXT,
    githubUrl TEXT,
    folderName TEXT
);

-- 2. 批次新增技能資料

-- [Document Skills]
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (1, 'docx', 'Word 文件助手 (docx)', 'Read, extract, and manipulate Word documents.', '讀取、擷取並操作 Microsoft Word (.docx) 文件內容。', 'Anthropic', 'Document Skills', '["Document","Word","Extraction"]', 0, '2025-01-01', '1.0.0', 'https://github.com/anthropics/skills/tree/main/skills/docx', 'docx');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (2, 'pdf', 'PDF 全能助手', 'Extract text, tables, metadata, merge & annotate PDFs.', '擷取文字、表格、元資料，並支援合併與標註 PDF 文件。', 'Anthropic', 'Document Skills', '["Document","PDF","Extraction"]', 0, '2025-01-05', '1.0.0', 'https://github.com/anthropics/skills/tree/main/skills/pdf', 'pdf');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (3, 'pptx', 'PowerPoint 簡報大師', 'Read, generate, and adjust slides, layouts, templates.', '讀取、生成並調整投影片內容、佈局與範本。', 'Anthropic', 'Document Skills', '["Document","PowerPoint","Slides"]', 0, '2025-01-10', '1.0.0', 'https://github.com/anthropics/skills/tree/main/skills/pptx', 'pptx');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (4, 'xlsx', 'Excel 數據專家', 'Spreadsheet manipulation: formulas, charts, data transformations.', '試算表操作：包含公式應用、圖表生成與數據轉換。', 'Anthropic', 'Document Skills', '["Document","Excel","Data"]', 0, '2025-01-15', '1.0.0', 'https://github.com/anthropics/skills/tree/main/skills/xlsx', 'xlsx');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (5, 'revealjs-skill', 'Reveal.js 網頁簡報製作', 'Generate polished, professional presentations using the Reveal.js HTML presentation framework.', '使用 Reveal.js HTML 簡報框架生成專業且精美的網頁式簡報。', 'ryanbbrown', 'Document Skills', '["Presentation","Reveal.js","HTML"]', 0, '2025-02-01', '1.0.0', NULL, 'revealjs-skill');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (100, 'xlsx', 'Excel 處理專家 (xlsx)', 'Use this skill any time a spreadsheet file is the primary input or output (Excel, CSV, TSV).', '當試算表文件（Excel、CSV、TSV）為主要輸入輸出時使用此技能。', 'Anthropic', 'Document Skills', '["Excel","CSV","Spreadsheet","Data"]', 0, '2025-03-03', '1.0.0', 'https://github.com/anthropics/skills/tree/main/skills/xlsx', 'xlsx');

-- [Development & Code Tools]
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (6, 'web-artifacts-builder', 'Web 藝術品開發工具箱', 'Suite of tools for creating elaborate, multi-component HTML artifacts using React, Tailwind, and shadcn/ui.', '一套用於使用 React、Tailwind 與 shadcn/ui 構建複雜多組件 HTML 作品的工具集。', 'Anthropic', 'Development & Code Tools', '["React","Tailwind","Artifacts"]', 0, '2025-01-20', '1.1.0', NULL, 'web-artifacts-builder');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (7, 'test-driven-development', 'TDD 測試驅動開發', 'Use when implementing any feature or bugfix, before writing implementation code.', '在撰寫實際邏輯程式碼前，用於實作功能或修復錯誤的測試導向開發流程。', 'obra', 'Development & Code Tools', '["TDD","Testing","Quality"]', 0, '2025-01-25', '1.0.0', 'https://github.com/obra/superpowers/tree/main/skills/test-driven-development', 'test-driven-development');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (8, 'claude-starter', 'Claude Code 啟動範本', 'Production-ready Claude Code configuration template with 40 auto-activating skills.', '生產級的 Claude Code 配置範本，內建 40 個自動啟用的技能。', 'raintree-technology', 'Development & Code Tools', '["Starter","Configuration","Template"]', 0, '2025-02-10', '1.5.0', NULL, 'claude-starter');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (12, 'oiloil-ui-ux-guide', 'OilOil UI/UX 設計規範', 'Modern UI/UX guidance and review skill with guide and review modes.', '現代化的 UI/UX 指引與審閱技能，包含指引與審查兩種模式。', 'oil-oil', 'Development & Code Tools', '["UI/UX","Design","Review"]', 0, '2025-02-20', '1.0.0', 'https://github.com/oil-oil/oiloil-ui-ux-guide', 'oiloil-ui-ux-guide');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (14, 'angular-architect', 'Angular 架構師', 'Build enterprise Angular apps with signals and standalone components.', '使用 Signals 與獨立組件 (Standalone) 構建企業級 Angular 應用。', 'Jeffallan', 'Development & Code Tools', '["Angular","Signals","Architecture"]', 0, '2025-02-25', '1.0.0', 'https://github.com/Jeffallan/claude-skills/tree/main/skills/angular-architect', 'angular-architect');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (15, 'api-designer', 'API 設計專家', 'Design REST/GraphQL APIs with OpenAPI 3.1 standards.', '遵循 OpenAPI 3.1 標準設計 REST 或 GraphQL API 接口。', 'Jeffallan', 'Development & Code Tools', '["API","OpenAPI","Design"]', 0, '2025-02-26', '1.0.0', 'https://github.com/Jeffallan/claude-skills/tree/main/skills/api-designer', 'api-designer');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (16, 'architecture-designer', '系統架構設計師', 'Architect scalable distributed systems and document ADRs.', '設計可擴展的分佈式系統架構，並撰寫架構決策紀錄 (ADR)。', 'Jeffallan', 'Development & Code Tools', '["System Design","ADR","Scalability"]', 0, '2025-02-27', '1.0.0', 'https://github.com/Jeffallan/claude-skills/tree/main/skills/architecture-designer', 'architecture-designer');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (17, 'cli-developer', 'CLI 工具開發專家', 'Build fast, intuitive cross-platform CLI tools.', '構建快速、直觀且支援跨平台的命令行介面 (CLI) 工具。', 'Jeffallan', 'Development & Code Tools', '["CLI","Terminal","DX"]', 0, '2025-03-01', '1.0.0', 'https://github.com/Jeffallan/claude-skills/tree/main/skills/cli-developer', 'cli-developer');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (36, 'embedded-systems', '嵌入式系統專家', 'Developing firmware for microcontrollers, implementing RTOS applications, or optimizing power consumption.', '開發微控制器韌體、實作實時作業系統 (RTOS) 應用，或優化功耗。', 'Jeffallan', 'Development & Code Tools', '["Embedded","Firmware","RTOS"]', 0, '2025-03-03', '1.0.0', 'https://github.com/Jeffallan/claude-skills/tree/main/skills/embedded-systems', 'embedded-systems');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (38, 'fastapi-expert', 'FastAPI 專家', 'Build high-performance async Python APIs with FastAPI and Pydantic V2.', '使用 FastAPI 與 Pydantic V2 構建高性能非同步 Python API。', 'Jeffallan', 'Development & Code Tools', '["Python","FastAPI","Async"]', 0, '2025-03-03', '1.0.0', 'https://github.com/Jeffallan/claude-skills/tree/main/skills/fastapi-expert', 'fastapi-expert');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (42, 'flutter-expert', 'Flutter 跨平台專家', 'Building cross-platform applications with Flutter 3+ and Dart.', '使用 Flutter 3+ 與 Dart 語言構建跨平台應用程式。', 'Jeffallan', 'Development & Code Tools', '["Flutter","Dart","Mobile"]', 0, '2025-03-03', '1.0.0', 'https://github.com/Jeffallan/claude-skills/tree/main/skills/flutter-expert', 'flutter-expert');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (43, 'frontend-design', '前端設計大師', 'Create distinctive, production-grade frontend interfaces with high design quality.', '創造具備高品質設計感、獨特且生產級的前端使用者介面。', 'Jeffallan', 'Development & Code Tools', '["Frontend","UI","Aesthetics"]', 0, '2025-03-03', '1.0.0', 'https://github.com/Jeffallan/claude-skills/tree/main/skills/frontend-design', 'frontend-design');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (44, 'fullstack-guardian', '全端安全守護者', 'Implementing features across frontend and backend with security built-in from the start.', '從頭開始將安全機制內建於前端與後端的功能實作中。', 'Jeffallan', 'Development & Code Tools', '["Fullstack","Security","API"]', 0, '2025-03-03', '1.0.0', 'https://github.com/Jeffallan/claude-skills/tree/main/skills/fullstack-guardian', 'fullstack-guardian');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (46, 'golang-pro', 'Go 語言專家', 'Building Go applications requiring concurrent programming, microservices, or high-performance systems.', '構建需要高併發程式設計、微服務或高性能系統的 Go 應用程式。', 'Jeffallan', 'Development & Code Tools', '["Go","Concurrency","Microservices"]', 0, '2025-03-03', '1.0.0', 'https://github.com/Jeffallan/claude-skills/tree/main/skills/golang-pro', 'golang-pro');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (47, 'graphql-architect', 'GraphQL 架構師', 'Designing GraphQL schemas, implementing Apollo Federation, or building real-time subscriptions.', '設計 GraphQL Schema、實作 Apollo Federation 或構建實時訂閱功能。', 'Jeffallan', 'Development & Code Tools', '["GraphQL","Apollo","Federation"]', 0, '2025-03-03', '1.0.0', 'https://github.com/Jeffallan/claude-skills/tree/main/skills/graphql-architect', 'graphql-architect');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (49, 'java-architect', 'Java 企業級架構師', 'Building enterprise Java applications with Spring Boot 3.x, microservices, or reactive programming.', '使用 Spring Boot 3.x、微服務或響應式程式設計構建企業級 Java 應用。', 'Jeffallan', 'Development & Code Tools', '["Java","Spring Boot","Enterprise"]', 0, '2025-03-03', '1.0.0', 'https://github.com/Jeffallan/claude-skills/tree/main/skills/java-architect', 'java-architect');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (50, 'php-pro', 'PHP 專家', 'Use when building PHP applications with modern PHP 8.3+ features, Laravel, or Symfony frameworks.', '使用現代 PHP 8.3+ 特性、Laravel 或 Symfony 框架開發 PHP 應用。', 'Jeffallan', 'Development & Code Tools', '["PHP","Laravel","Symfony"]', 0, '2025-03-03', '1.0.0', 'https://github.com/Jeffallan/claude-skills/tree/main/skills/php-pro', 'php-pro');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (51, 'python-pro', 'Python 專家', 'Use when building Python 3.11+ applications requiring type safety, async programming, or production-grade patterns.', '開發 Python 3.11+ 應用，涵蓋型別安全、非同步設計與生產級模式。', 'Jeffallan', 'Development & Code Tools', '["Python","Async","Type Safety"]', 0, '2025-03-03', '1.0.0', 'https://github.com/Jeffallan/claude-skills/tree/main/skills/python-pro', 'python-pro');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (52, 'rails-expert', 'Ruby on Rails 專家', 'Use when building Rails 7+ web applications with Hotwire, real-time features, or background job processing.', '使用 Hotwire、實時功能或背景任務處理構建 Rails 7+ 網頁應用。', 'Jeffallan', 'Development & Code Tools', '["Rails","Ruby","Hotwire"]', 0, '2025-03-03', '1.0.0', 'https://github.com/Jeffallan/claude-skills/tree/main/skills/rails-expert', 'rails-expert');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (53, 'react-expert', 'React 18+ 專家', 'Use when building React 18+ applications requiring component architecture, hooks patterns, or state management.', '用於建構 React 18+ 應用程式，涵蓋元件架構、Hooks 模式與狀態管理。', 'Jeffallan', 'Development & Code Tools', '["React","Hooks","TypeScript"]', 0, '2025-03-03', '1.0.0', 'https://github.com/Jeffallan/claude-skills/tree/main/skills/react-expert', 'react-expert');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (54, 'react-native-expert', 'React Native 移動端專家', 'Use when building cross-platform mobile applications with React Native or Expo.', '使用 React Native 或 Expo 構建跨平台移動應用程式。', 'Jeffallan', 'Development & Code Tools', '["React Native","Expo","Mobile"]', 0, '2025-03-03', '1.0.0', 'https://github.com/Jeffallan/claude-skills/tree/main/skills/react-native-expert', 'react-native-expert');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (55, 'receiving-code-review', '接收程式碼審閱 (Code Review)', 'Use when receiving code review feedback, before implementing suggestions, especially if feedback seems unclear or technically questionable.', '在接收審閱回饋時使用，協助在實作建議前釐清不明確或具技術爭議的部分。', 'Jeffallan', 'Development & Code Tools', '["Code Review","Workflow","Quality"]', 0, '2025-03-03', '1.0.0', 'https://github.com/obra/superpowers/tree/main/skills/receiving-code-review', 'receiving-code-review');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (56, 'requesting-code-review', '發起程式碼審閱 (Code Review)', 'Use when completing tasks, implementing major features, or before merging to verify work meets requirements.', '在完成任務、實作重大功能或合併前，確保工作內容符合需求規範。', 'Jeffallan', 'Development & Code Tools', '["Code Review","Verification","Workflow"]', 0, '2025-03-03', '1.0.0', 'https://github.com/obra/superpowers/tree/main/skills/requesting-code-review', 'requesting-code-review');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (70, 'rust-engineer', 'Rust 工程師', 'Use when building Rust applications requiring memory safety, systems programming, or zero-cost abstractions.', '開發 Rust 應用，專注於記憶體安全、系統程式設計與零成本抽象。', 'Jeffallan', 'Development & Code Tools', '["Rust","Systems","Performance"]', 0, '2025-03-03', '1.0.0', 'https://github.com/Jeffallan/claude-skills/tree/main/skills/rust-engineer', 'rust-engineer');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (71, 'salesforce-developer', 'Salesforce 開發專家', 'Developing Salesforce applications, Apex code, Lightning Web Components, SOQL queries, or integrations.', '開發 Salesforce 應用、Apex 程式碼、LWC、SOQL 查詢或系統整合。', 'Jeffallan', 'Development & Code Tools', '["Salesforce","Apex","CRM"]', 0, '2025-03-03', '1.0.0', 'https://github.com/Jeffallan/claude-skills/tree/main/skills/salesforce-developer', 'salesforce-developer');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (72, 'shopify-expert', 'Shopify 電商專家', 'Building Shopify themes, apps, custom storefronts, or e-commerce solutions.', '開發 Shopify 主題、App、自定義店面或電商解決方案。', 'Jeffallan', 'Development & Code Tools', '["Shopify","Liquid","E-commerce"]', 0, '2025-03-03', '1.0.0', 'https://github.com/Jeffallan/claude-skills/tree/main/skills/shopify-expert', 'shopify-expert');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (73, 'spec-miner', '規範挖掘專家 (Spec Miner)', 'Understanding legacy or undocumented systems, creating documentation, or extracting specifications from implementations.', '理解遺留或缺乏文件的系統，建立文件並從現有實作中提取技術規範。', 'Jeffallan', 'Development & Code Tools', '["Reverse Engineering","Documentation","Legacy"]', 0, '2025-03-03', '1.0.0', 'https://github.com/Jeffallan/claude-skills/tree/main/skills/spec-miner', 'spec-miner');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (74, 'spring-boot-engineer', 'Spring Boot 專家', 'Building Spring Boot 3.x applications, microservices, or reactive Java applications.', '構建 Spring Boot 3.x 應用程式、微服務或響應式 Java 應用。', 'Jeffallan', 'Development & Code Tools', '["Spring Boot","Java","Backend"]', 0, '2025-03-03', '1.0.0', 'https://github.com/Jeffallan/claude-skills/tree/main/skills/spring-boot-engineer', 'spring-boot-engineer');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (81, 'sre-engineer', 'SRE 維運工程師', 'Use when defining SLIs/SLOs, managing error budgets, or building reliable systems at scale.', '用於定義 SLIs/SLOs、管理錯誤預算或構建大規模可靠系統。', 'Jeffallan', 'Development & Code Tools', '["SRE","Reliability","Monitoring"]', 0, '2025-03-03', '1.0.0', 'https://github.com/Jeffallan/claude-skills/tree/main/skills/sre-engineer', 'sre-engineer');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (83, 'swift-expert', 'Swift 專家', 'Use when building iOS/macOS applications with Swift 5.9+, SwiftUI, or async/await concurrency.', '使用 Swift 5.9+、SwiftUI 或非同步併發構建 iOS/macOS 應用。', 'Jeffallan', 'Development & Code Tools', '["Swift","iOS","SwiftUI"]', 0, '2025-03-03', '1.0.0', 'https://github.com/Jeffallan/claude-skills/tree/main/skills/swift-expert', 'swift-expert');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (84, 'systematic-debugging', '系統化除錯專家', 'Use when encountering any bug, test failure, or unexpected behavior, before proposing fixes.', '在提出修復前，針對任何 Bug 或異常行為進行系統化分析。', 'Jeffallan', 'Development & Code Tools', '["Debugging","RC","Methodology"]', 0, '2025-03-03', '1.0.0', 'https://github.com/obra/superpowers/tree/main/skills/systematic-debugging', 'systematic-debugging');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (85, 'terraform-engineer', 'Terraform IaC 工程師', 'Use when implementing infrastructure as code with Terraform across AWS, Azure, or GCP.', '使用 Terraform 在不同雲端平台上實作基礎設施即程式碼 (IaC)。', 'Jeffallan', 'Development & Code Tools', '["Terraform","IaC","Infra"]', 0, '2025-03-03', '1.0.0', 'https://github.com/Jeffallan/claude-skills/tree/main/skills/terraform-engineer', 'terraform-engineer');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (86, 'test-master', '測試大師', 'Use when writing tests, creating test strategies, or building automation frameworks.', '用於撰寫測試、建立測試策略或構建自動化測試框架。', 'Jeffallan', 'Development & Code Tools', '["Testing","QA","Automation"]', 0, '2025-03-03', '1.0.0', 'https://github.com/Jeffallan/claude-skills/tree/main/skills/test-master', 'test-master');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (89, 'typescript-pro', 'TypeScript 專業專家', 'Use when building TypeScript applications requiring advanced type systems or generics.', '構建需要進階型別系統或泛型應用的 TypeScript 應用程式。', 'Jeffallan', 'Development & Code Tools', '["TypeScript","Generics","Typing"]', 0, '2025-03-03', '1.0.0', 'https://github.com/Jeffallan/claude-skills/tree/main/skills/typescript-pro', 'typescript-pro');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (92, 'verification-before-completion', '完成前驗證機制', 'Use when about to claim work is complete, fixed, or passing, before committing.', '在提交程式碼前，驗證工作是否已真正完成、修復或通過測試。', 'SKILLS All-in-one', 'Development & Code Tools', '["Validation","Testing","Verification"]', 0, '2025-03-03', '1.0.0', 'https://github.com/obra/superpowers/tree/main/skills/verification-before-completion', 'verification-before-completion');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (93, 'vue-expert', 'Vue 3 專家', 'Use when building Vue 3 applications with Composition API, Nuxt 3, or Quasar.', '使用 Composition API、Nuxt 3 或 Quasar 構建 Vue 3 應用。', 'Jeffallan', 'Development & Code Tools', '["Vue","Composition API","Nuxt"]', 0, '2025-03-03', '1.0.0', 'https://github.com/Jeffallan/claude-skills/tree/main/skills/vue-expert', 'vue-expert');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (94, 'vue-expert-js', 'Vue 3 JS 專家 (無 TS)', 'Use when building Vue 3 applications with JavaScript only (no TypeScript).', '使用純 JavaScript (無 TypeScript) 構建 Vue 3 應用程式。', 'Jeffallan', 'Development & Code Tools', '["Vue","JavaScript","JSDoc"]', 0, '2025-03-03', '1.0.0', 'https://github.com/Jeffallan/claude-skills/tree/main/skills/vue-expert-js', 'vue-expert-js');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (96, 'websocket-engineer', 'WebSocket 工程師', 'Use when building real-time communication systems with WebSockets or Socket.IO.', '使用 WebSockets 或 Socket.IO 構建實時通訊系統。', 'Jeffallan', 'Development & Code Tools', '["WebSocket","Socket.IO","Real-time"]', 0, '2025-03-03', '1.0.0', 'https://github.com/Jeffallan/claude-skills/tree/main/skills/websocket-engineer', 'websocket-engineer');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (97, 'wordpress-pro', 'WordPress 專家', 'Use when developing WordPress themes, plugins, customizing Gutenberg blocks, or optimizing WordPress performance.', '開發 WordPress 主題、外掛、客製化區塊或優化效能。', 'Jeffallan', 'Development & Code Tools', '["WordPress","WooCommerce","Gutenberg"]', 0, '2025-03-03', '1.0.0', 'https://github.com/Jeffallan/claude-skills/tree/main/skills/wordpress-pro', 'wordpress-pro');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (98, 'writing-plans', '實作計畫撰寫專家', 'Use when you have a spec or requirements for a multi-step task, before touching code. Write comprehensive implementation plans assuming the engineer has zero context.', '在撰寫程式碼前，針對多步驟任務編寫全面的實作計畫。', 'Jeffallan', 'Development & Code Tools', '["Planning","Implementation","Workflow"]', 0, '2025-03-03', '1.0.0', 'https://github.com/obra/superpowers/tree/main/skills/writing-plans', 'writing-plans');

-- [Data & Analysis]
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (9, 'csv-data-summarizer', 'CSV 數據總結員', 'Automatically analyzes CSVs: columns, distributions, missing data, correlations.', '自動分析 CSV 文件：包含欄位定義、數據分佈、缺失值檢測與相關性分析。', 'coffeefuelbump', 'Data & Analysis', '["CSV","Data","Summary"]', 0, '2025-01-30', '1.0.2', NULL, 'csv-data-summarizer');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (10, 'postgres', 'PostgreSQL 查詢專家', 'Execute safe read-only SQL queries against PostgreSQL databases.', '針對 PostgreSQL 資料庫執行安全的唯讀 SQL 查詢。', 'sanjay3290', 'Data & Analysis', '["SQL","PostgreSQL","Database"]', 0, '2025-02-05', '1.0.0', NULL, 'postgres');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (29, 'database-optimizer', '資料庫優化大師', 'investigating slow queries, analyzing execution plans, and index design.', '調查慢查詢、分析執行計畫並進行索引設計優化。', 'Jeffallan', 'Data & Analysis', '["Database","SQL","Optimization"]', 0, '2025-03-03', '1.0.0', 'https://github.com/Jeffallan/claude-skills/tree/main/skills/database-optimizer', 'database-optimizer');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (40, 'fine-tuning-expert', 'LLM 微調專家', 'Fine-tuning LLMs, training custom models, or optimizing model performance for specific tasks.', '進行大語言模型 (LLM) 微調、訓練自定義模型或針對特定任務優化模型效能。', 'Jeffallan', 'Data & Analysis', '["LLM","AI","ML"]', 0, '2025-03-03', '1.0.0', 'https://github.com/Jeffallan/claude-skills/tree/main/skills/fine-tuning-expert', 'fine-tuning-expert');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (57, 'postgres-pro', 'PostgreSQL 專業顧問', 'Use when optimizing PostgreSQL queries, configuring replication, or implementing advanced database features.', '優化 PostgreSQL 查詢、配置資料複製或實作進階資料庫功能。', 'Jeffallan', 'Data & Analysis', '["PostgreSQL","SQL","Optimization"]', 0, '2025-03-03', '1.0.0', 'https://github.com/Jeffallan/claude-skills/tree/main/skills/postgres-pro', 'postgres-pro');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (58, 'rag-architect', 'RAG 架構師', 'Use when building RAG systems, vector databases, or knowledge-grounded AI applications.', '構建檢索增強生成 (RAG) 系統、向量資料庫或知識庫驅動的 AI 應用。', 'Jeffallan', 'Data & Analysis', '["RAG","Vector DB","AI"]', 0, '2025-03-03', '1.0.0', 'https://github.com/Jeffallan/claude-skills/tree/main/skills/rag-architect', 'rag-architect');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (77, 'spark-engineer', 'Apache Spark 工程師', 'Building Apache Spark applications, distributed data processing pipelines, or optimizing big data workloads.', '開發 Apache Spark 應用、分佈式資料處理流水線過優化大數據工作負載。', 'Jeffallan', 'Data & Analysis', '["Spark","Big Data","ETL"]', 0, '2025-03-03', '1.0.0', 'https://github.com/Jeffallan/claude-skills/tree/main/skills/spark-engineer', 'spark-engineer');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (80, 'sql-pro', 'SQL 專業專家', 'Use when optimizing SQL queries, designing database schemas, or tuning database performance.', '用於優化 SQL 查詢、設計資料庫架構或調校資料庫效能。', 'Jeffallan', 'Data & Analysis', '["SQL","Database","Optimization"]', 0, '2025-03-03', '1.0.0', 'https://github.com/Jeffallan/claude-skills/tree/main/skills/sql-pro', 'sql-pro');

-- [Media & Content]
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (18, 'algorithmic-art', '演算法藝術家', 'Generate living algorithms and generative art using p5.js.', '使用 p5.js 生成具備生命感的演算法與生成藝術作品。', 'Anthropic', 'Media & Content', '["Generative Art","p5.js","Creative"]', 0, '2025-02-15', '1.0.0', 'https://github.com/anthropics/skills/tree/main/skills/algorithmic-art', 'algorithmic-art');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (19, 'canvas-design', '畫布設計專家', 'Create museum-quality visual designs and artistic canvases.', '創造具備博物館品質的視覺設計與藝術畫布作品。', 'Anthropic', 'Media & Content', '["Design","Art","Visual"]', 0, '2025-02-18', '1.0.0', 'https://github.com/anthropics/skills/tree/main/skills/canvas-design', 'canvas-design');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (20, 'brand-guidelines', '品牌規範助手', 'Apply Anthropic official brand colors and typography to any artifact.', '將 Anthropic 官方品牌色彩與字體應用於任何作品中。', 'Anthropic', 'Media & Content', '["Branding","Styling","Guidelines"]', 0, '2025-01-10', '1.0.0', 'https://github.com/anthropics/skills/tree/main/skills/brand-guidelines', 'brand-guidelines');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (45, 'game-developer', '遊戲開發專家', 'Building game systems, implementing Unity/Unreal features, or optimizing game performance.', '構建遊戲系統、實作 Unity/Unreal 功能或優化遊戲效能。', 'Jeffallan', 'Media & Content', '["Unity","Unreal","GameDev"]', 0, '2025-03-03', '1.0.0', 'https://github.com/Jeffallan/claude-skills/tree/main/skills/game-developer', 'game-developer');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (78, 'slack-gif-creator', 'Slack GIF 創作工具', 'Create animated GIFs optimized for Slack with dimensions, validation tools, and easing functions.', '創建專為 Slack 優化的動畫 GIF，內建尺寸校驗與過渡函數工具。', 'SKILLS All-in-one', 'Media & Content', '["Slack","GIF","Design"]', 0, '2025-03-03', '1.0.0', NULL, 'slack-gif-creator');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (88, 'theme-factory', '主題工廠', 'Toolkit for styling artifacts with professional themes, colors, and fonts.', '為作品提供專業主題、配色與字體配置的工具包。', 'Jeffallan', 'Media & Content', '["Design","Themes","Styling"]', 0, '2025-03-03', '1.0.0', 'https://github.com/Jeffallan/claude-skills/tree/main/skills/theme-factory', 'theme-factory');

-- [Writing & Research]
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (11, 'article-extractor', '文章擷取工具', 'Extract full article text and metadata from web pages.', '從網頁中完整擷取文章正文與元資料。', 'michalparkola', 'Writing & Research', '["Scraping","Metadata","Web"]', 0, '2025-02-15', '1.0.0', NULL, 'article-extractor');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (21, 'brainstorming', '腦力激盪顧問', 'Transform rough ideas into fully-formed designs through structured questioning.', '透過結構化的提問，將初步構思轉化為完整的設計方案。', 'obra', 'Writing & Research', '["Ideas","Requirements","Design"]', 0, '2025-01-05', '1.0.0', 'https://github.com/obra/superpowers/tree/main/skills/brainstorming', 'brainstorming');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (34, 'doc-coauthoring', '文件協同撰寫 (Co-authoring)', 'Guide users through a structured workflow for co-authoring documentation.', '引導使用者透過結構化流程進行文件的協同撰寫。', 'SKILLS All-in-one', 'Writing & Research', '["Documentation","Co-authoring","Writing"]', 0, '2025-03-03', '1.0.0', NULL, 'doc-coauthoring');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (48, 'internal-comms', '內部通訊專家', 'Write internal company communications (status reports, newsletters, FAQs, incident reports).', '撰寫公司內部通訊內容（進度報告、電子報、FAQ、事故報告）。', 'Jeffallan', 'Writing & Research', '["Comms","Internal","Writing"]', 0, '2025-03-03', '1.0.0', 'https://github.com/Jeffallan/claude-skills/tree/main/skills/internal-comms', 'internal-comms');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (87, 'the-fool', '愚者 (結構化批判)', 'Use when challenging ideas, plans, decisions, or proposals using structured critical reasoning.', '透過結構化批判性推理，挑戰既有的構思、計畫或決策。', 'Jeffallan', 'Writing & Research', '["Critical Thinking","Red Team","Reasoning"]', 0, '2025-03-03', '1.0.0', 'https://github.com/Jeffallan/claude-skills/tree/main/skills/the-fool', 'the-fool');

-- [Security & Web Testing]
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (23, 'chaos-engineer', '混沌工程師', 'Design chaos experiments and build systems that get stronger under stress.', '設計混沌實驗，構建在壓力下能變得更強韌的系統。', 'Jeffallan', 'Security & Web Testing', '["Chaos Engineering","Resilience","Testing"]', 0, '2025-03-02', '1.0.0', 'https://github.com/Jeffallan/claude-skills/tree/main/skills/chaos-engineer', 'chaos-engineer');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (75, 'secure-code-guardian', '安全程式碼守護者', 'Implementing authentication/authorization, securing user input, or preventing OWASP Top 10 vulnerabilities.', '實作身份驗證、保護使用者輸入，並防範 OWASP Top 10 漏洞。', 'Jeffallan', 'Security & Web Testing', '["Security","Auth","OWASP"]', 0, '2025-03-03', '1.0.0', 'https://github.com/Jeffallan/claude-skills/tree/main/skills/secure-code-guardian', 'secure-code-guardian');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (76, 'security-reviewer', '安全性審閱者', 'Conducting security audits, reviewing code for vulnerabilities, or analyzing infrastructure security.', '進行安全審查、檢查程式碼漏洞或分析基礎設施安全性。', 'Jeffallan', 'Security & Web Testing', '["Audit","Vulnerability","Pentest"]', 0, '2025-03-03', '1.0.0', 'https://github.com/Jeffallan/claude-skills/tree/main/skills/security-reviewer', 'security-reviewer');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (95, 'webapp-testing', 'Web 應用測試工具', 'Toolkit for interacting with and testing local web applications using Playwright.', '使用 Playwright 與本地 Web 應用互動並進行測試的工具包。', 'Jeffallan', 'Security & Web Testing', '["Testing","Playwright","Web"]', 0, '2025-03-03', '1.0.0', 'https://github.com/Jeffallan/claude-skills/tree/main/skills/webapp-testing', 'webapp-testing');

-- [Utility & Automation]
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (32, 'dispatching-parallel-agents', '並行 Agent 調度員', 'Dispatch one agent per independent problem domain to work concurrently.', '針對獨立的問題領域分配不同的 Agent 進行併行作業。', 'SKILLS All-in-one', 'Utility & Automation', '["Agent","Parallel","Multi-task"]', 0, '2025-03-03', '1.0.0', 'https://github.com/obra/superpowers/tree/main/skills/dispatching-parallel-agents', 'dispatching-parallel-agents');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (37, 'executing-plans', '執行計畫專家', 'Execute a written implementation plan with review checkpoints.', '執行預定的實作計畫，並包含關鍵審核節點。', 'Jeffallan', 'Utility & Automation', '["Workflow","Execution","Planning"]', 0, '2025-03-03', '1.0.0', 'https://github.com/obra/superpowers/tree/main/skills/executing-plans', 'executing-plans');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (41, 'finishing-a-development-branch', '開發分支結案助手', 'Guide completion of development work by presenting structured options for merge, PR, or cleanup.', '引導完成開發工作，提供合併、PR 或清理分支的結構化選項。', 'Jeffallan', 'Utility & Automation', '["Git","Workflow","PR"]', 0, '2025-03-03', '1.0.0', 'https://github.com/obra/superpowers/tree/main/skills/finishing-a-development-branch', 'finishing-a-development-branch');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (79, 'skill-creator', '技能創造者 (Skill Creator)', 'Create new skills, modify and improve existing skills, and measure skill performance with evals.', '創造新技能、修改現有技能，並透過評估機制衡量技能效能。', 'SKILLS All-in-one', 'Utility & Automation', '["Agent","Skills","Development"]', 0, '2025-03-03', '1.0.0', NULL, 'skill-creator');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (13, 'skill-master', 'AI 技能大師 (Skill Master)', 'The ultimate AI Agent Skill Master for analyzing, architecting, and authoring skills.', '專為分析、設計與編寫 AI Agent 技能而生的終極大師工具。', 'SKILLS All-in-one', 'Utility & Automation', '["Agent","Architecture","Writing"]', 0, '2026-03-03', '1.0.0', NULL, 'skill-master');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (82, 'subagent-driven-development', '子 Agent 驅動開發 (SDD)', 'Use when executing implementation plans with independent tasks in the current session.', '在執行具有獨立任務的實作計畫時，透過子 Agent 進行開發。', 'SKILLS All-in-one', 'Utility & Automation', '["Workflow","Agent","Implementation"]', 0, '2025-03-03', '1.0.0', 'https://github.com/obra/superpowers/tree/main/skills/subagent-driven-development', 'subagent-driven-development');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (90, 'using-git-worktrees', 'Git Worktree 實戰專家', 'Use when starting feature work that needs isolation from current workspace or before executing plans.', '在需要與目前工作區隔離的情況下開始新功能開發或執行計畫。', 'Jeffallan', 'Utility & Automation', '["Git","Worktree","Workflow"]', 0, '2025-03-03', '1.0.0', 'https://github.com/obra/superpowers/tree/main/skills/using-git-worktrees', 'using-git-worktrees');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (91, 'using-superpowers', '啟動超能力 (技能調用)', 'Use when starting any conversation - establishes how to find and use skills.', '在對話開始時使用 — 建立如何尋找並調用技能的標準流程。', 'SKILLS All-in-one', 'Utility & Automation', '["Agent","Skill","Workflow"]', 0, '2025-03-03', '1.0.0', 'https://github.com/obra/superpowers/tree/main/skills/using-superpowers', 'using-superpowers');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (99, 'writing-skills', '技能編寫專家 (Skill Author)', 'Use when creating new skills, editing existing skills, or verifying skills work before deployment.', '用於創建新技能、編輯現有技能或在部署前驗證技能功能。', 'Jeffallan', 'Utility & Automation', '["Skills","Documentation","TDD","Automation"]', 0, '2025-03-03', '1.0.0', 'https://github.com/obra/superpowers/tree/main/skills/writing-skills', 'writing-skills');

-- [Collaboration & Project Management]
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (22, 'atlassian-mcp', 'Atlassian 工作流專家', 'Integrate Jira and Confluence workflows via Model Context Protocol.', '透過 MCP 協定整合 Jira 與 Confluence 的工作流程。', 'Jeffallan', 'Collaboration & Project Management', '["Jira","Confluence","MCP"]', 0, '2025-02-28', '1.0.0', 'https://github.com/Jeffallan/claude-skills/tree/main/skills/atlassian-mcp', 'atlassian-mcp');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (39, 'feature-forge', '功能鍛造者 (Feature Forge)', 'Gathering requirements, conducting workshops, and defining comprehensive feature specifications.', '收集需求、主持工作坊並定義全面的功能規格書。', 'Jeffallan', 'Collaboration & Project Management', '["Requirements","Product","Planning"]', 0, '2025-03-03', '1.0.0', 'https://github.com/Jeffallan/claude-skills/tree/main/skills/feature-forge', 'feature-forge');

-- [Infrastructure & Cloud]
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (102, 'aws-mcp-setup', 'AWS MCP 配置助手', 'Configure AWS Documentation MCP server to query up-to-date AWS knowledge.', '配置 AWS 文件 MCP 伺服器，以查詢最新的 AWS 知識、API 與最佳實踐。', 'zxkane', 'Infrastructure & Cloud', '["AWS","MCP","Setup","Cloud"]', 0, '2026-03-04', '1.0.0', 'https://github.com/zxkane/aws-skills/tree/main/plugins/aws-common/skills/aws-mcp-setup', 'aws-mcp-setup');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (103, 'aws-cdk-development', 'AWS CDK 開發專家', 'AWS Cloud Development Kit (CDK) expert for building cloud infrastructure with TypeScript/Python.', 'AWS 雲端開發套件 (CDK) 專家，使用 TypeScript 或 Python 構建雲端基礎設施。', 'zxkane', 'Infrastructure & Cloud', '["AWS","CDK","IaC","TypeScript","Cloud"]', 0, '2026-03-04', '1.0.0', 'https://github.com/zxkane/aws-skills/tree/main/plugins/aws-cdk/skills/aws-cdk-development', 'aws-cdk-development');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (104, 'aws-cost-operations', 'AWS 成本與維運專家', 'AWS cost optimization, monitoring, and operational best practices.', 'AWS 成本優化、監控與維運最佳實踐，包含帳單分析與資源評估。', 'zxkane', 'Infrastructure & Cloud', '["AWS","Cost","Operations","Monitoring","Cloud"]', 0, '2026-03-04', '1.0.0', 'https://github.com/zxkane/aws-skills/tree/main/plugins/aws-cost-ops/skills/aws-cost-operations', 'aws-cost-operations');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (105, 'aws-serverless-eda', 'AWS Serverless 與事件驅動架構', 'AWS serverless and event-driven architecture expert based on Well-Architected Framework.', 'AWS Serverless 與事件驅動架構專家，專精於 Lambda, API Gateway 與 EventBridge。', 'zxkane', 'Infrastructure & Cloud', '["AWS","Serverless","EDA","Lambda","Cloud"]', 0, '2026-03-04', '1.0.0', 'https://github.com/zxkane/aws-skills/tree/main/plugins/serverless-eda/skills/aws-serverless-eda', 'aws-serverless-eda');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (106, 'aws-agentic-ai', 'AWS Bedrock Agentic AI 專家', 'AWS Bedrock AgentCore comprehensive expert for deploying and managing AI agents.', 'AWS Bedrock AgentCore 全方位專家，用於部署與管理 Bedrock AI 代理。', 'zxkane', 'Infrastructure & Cloud', '["AWS","Bedrock","AI","Agents","Cloud"]', 0, '2026-03-04', '1.0.0', 'https://github.com/zxkane/aws-skills/tree/main/plugins/aws-agentic-ai/skills/aws-agentic-ai', 'aws-agentic-ai');

-- [New Batch From Claude Starter]
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (107, 'aptos', 'Aptos & Move 專家', 'Aptos blockchain and Move language expert.', 'Aptos 區塊鏈與 Move 程式語言專家，涵蓋智能合約開發與代幣標準。', 'raintree', 'Web3 & Blockchain', '["Aptos","Move","Blockchain","Smart Contract"]', 0, '2026-03-04', '1.0.0', 'https://github.com/raintree-technology/claude-starter/tree/main/skills/aptos', 'aptos');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (108, 'helius', 'Solana Helius 專家', 'Helius Solana RPC and API expert.', 'Helius Solana 基礎設施專家，提供高性能 RPC、DAS API 與即時數據串流。', 'raintree', 'Web3 & Blockchain', '["Solana","Helius","RPC","NFT"]', 0, '2026-03-04', '1.0.0', 'https://github.com/raintree-technology/claude-starter/tree/main/skills/helius', 'helius');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (109, 'plaid', 'Plaid 銀行 API 專家', 'Plaid banking API expert for financial data integration.', 'Plaid 金融 API 專家，協助整合銀行連線、交易歷史與身份驗證。', 'raintree', 'Finance & Payments', '["Plaid","Fintech","Banking","API"]', 0, '2026-03-04', '1.0.0', 'https://github.com/raintree-technology/claude-starter/tree/main/skills/plaid', 'plaid');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (110, 'stripe', 'Stripe 支付專家', 'Stripe Payments Skill. Expertise in Stripe API integration.', 'Stripe 支付整合專家，涵蓋結帳流程、訂閱管理與 Webhooks。', 'raintree', 'Finance & Payments', '["Stripe","Payments","Checkout","SaaS"]', 0, '2026-03-04', '1.0.0', 'https://github.com/raintree-technology/claude-starter/tree/main/.claude/skills/stripe', 'stripe');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (111, 'whop', 'Whop 數位產品專家', 'Whop platform expert for digital products and memberships.', 'Whop 平台專家，協助數位產品銷售、會員管理與社群變現。', 'raintree', 'SaaS & Backend', '["Whop","Memberships","Digital Products","SaaS"]', 0, '2026-03-04', '1.0.0', 'https://github.com/raintree-technology/claude-starter/tree/main/skills/whop', 'whop');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (112, 'supabase', 'Supabase 全端專家', 'Supabase Backend Skill. Expertise in Auth, Database, and Storage.', 'Supabase 全端後端專家，專精於 Auth、PostgreSQL、Storage 與 Edge Functions。', 'raintree', 'SaaS & Backend', '["Supabase","PostgreSQL","Backend","Auth"]', 0, '2026-03-04', '1.0.0', 'https://github.com/raintree-technology/claude-starter/tree/main/.claude/skills/supabase', 'supabase');
INSERT INTO Skill (id, name, nameZh, description, descriptionZh, author, category, tags, downloadCount, createdAt, version, githubUrl, folderName) VALUES (113, 'move-code-quality', 'Move 代碼質量檢查員', 'Analyzes Move language packages against the official Move Book Code Quality Checklist.', '根據官方 Move Book 代碼質量清單分析 Move 語言包，確保符合 Move 2024 Edition 最佳實踐。', '1NickPappas', 'Web3 & Blockchain', '["Move","Sui","Code Quality","Audit"]', 0, '2026-03-04', '1.0.0', 'https://github.com/1NickPappas/move-code-quality-skill', 'move-code-quality-skill');
